spring.application.name=veterinariaIntegrador
spring.datasource.url=jdbc:mysql://localhost:3306/veterianarioIntegrador_fel
spring.datasource.username=root
spring.datasource.password=Okapis2205.

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8080